#The colors for blocks used when rendering their result bounding box
#by block name. Each entry must be a key-value pair separated by a `=`,
#with the key being the tag name and the value being the hexadecimal
#RGB value of the color.
blockColors = []
#The colors for blocks used when rendering their result bounding box
#by block tag. See `blockColors` for format entries have to be in.
blockTagColors = ["c:diamond_ores=0x5cdbd5", "c:gold_ores=0xfaee4d", "c:iron_ores=0x664c33", "c:nickel_ores=0x6699d8", "c:tin_ores=0x4c7f99", "c:coal_ores=0x4c4c4c", "c:lead_ores=0x4c3e5c", "c:redstone_ores=0x993333", "c:copper_ores=0x9f5224", "c:platinum_ores=0xd1b1a1", "c:silver_ores=0x999999", "c:quartz_ores=0xfffcf5", "c:emerald_ores=0xd93a", "c:lapis_ores=0x4a80ff"]
#The colors for fluids used when rendering their result bounding box
#by fluid name. See `blockColors` for format entries have to be in.
fluidColors = []
#The colors for fluids used when rendering their result bounding box
#by fluid tag. See `blockColors` for format entries have to be in.
fluidTagColors = ["minecraft:lava=0x9f5224", "minecraft:water=0x4040ff"]

